# Configuration du Consumer
spring.application.name=consumer-service

# Configuration RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Désactiver l'auto-configuration de la DataSource (pas de base de données pour ce consumer)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Port du serveur web (différent du Producer)
server.port=8081
